Contactmeform
ecekpo/Portfolio pull request #3
Opened 2022-06-08 11:40 UTC by ecekpo

I add a contact form to my portfolio and the portfolio of my coding partner.
I Made sure that I guide the users' experience in a way that helps them fill in the form without frustration.

2022-06-08 15:34 UTC, Emmyn5600 requested changes
Hi @ecekpo @Dev-inspired @Ngufor-emmanuella 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Please fix the eslint errors.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-06-08 16:29 UTC, tufoinnkuo10 commented on index.html
> +                          <button type="submit" id="contact-btn">Get in touch</button>
- [ ] kindly add the hover interaction on the button and add the size so it looks like the figma version.

2022-06-08 16:30 UTC, tufoinnkuo10 commented on index.html
> +                        <h4 class="Contact-me">Contact me</h4>
- [ ] please use the correct background image for the contact section

2022-06-09 01:51 UTC, Kakalanp approved these changes
# STATUS: APPROVED :green_circle: 

### Your project is approved @ecekpo! :tada: 

There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :clinking_glasses: 

<img src="https://media.giphy.com/media/slOhiKAVFgwr6/giphy-downsized.gif" alt="almost there">

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-09 01:51 UTC, Kakalanp commented on README.md
> +- LinkedIn: [LinkedIn](https://www.linkedin.com/in/emem-ekpo-857135234/)
[OPTIONAL]

Consider removing unnecessary fields on your README file, remember that this file is often your first chance to make you project look professional :briefcase:

2022-06-09 01:56 UTC, merged