Add desktop-version
ecekpo/Portfolio pull request #4
Opened 2022-06-09 19:04 UTC by ecekpo

Added desktop-version

2022-06-09 19:26 UTC, Kandy-Peter reviewed
# STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @ecekpo  
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that has some issues needed to be fixed before reviewing it:
- [ ] Make sure to give your PR a meaningful description of what you implemented in this milestone, so it will look professional as it is described in this [article](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

- [ ] Ensure that all LInters are greens(i.e No linter that failed).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

---
Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

---
_Invalid Code Review Request **Does not count** into the code reviews limit._

2022-06-09 23:05 UTC, ishimwezachee requested changes
Hi @ecekpo   , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Github flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Ishimwe Zachee  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
(Not automatically expanded because 3 MB is too large. You can [expand it anyway](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966) or [open it in a new window](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966).)

2022-06-09 23:05 UTC, ishimwezachee commented on index.html
> +                <button type="submit" class="click" value="Submit">Get In Touch</button>
- [ ] You've done an incredible job to apply the requirement of the project, but you also have to match your design to the one provided from figma design.  Your buttons seemed to be position in wrong place. please fix it to match to the provided design. 
![image](https://user-images.githubusercontent.com/43877689/172958959-94d8497a-56bd-4e0c-85a1-5a00513b0e5b.png)

![image](https://user-images.githubusercontent.com/43877689/172959059-4b8fa618-ddfb-4a3d-a87e-e543e1265900.png)

2022-06-09 23:05 UTC, ishimwezachee commented on index.html
> +            <a href="#">My Logo</a>
- [ ]  You should add the margin similar to the one provided from Figma design. 
![image](https://user-images.githubusercontent.com/43877689/172959331-a231d0d2-2117-4ce2-b42c-bad297907f5d.png)

2022-06-10 09:56 UTC, elyor-doniyorov approved these changes
Hi @ecekpo, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ There are no linter errors
✔️ Your design matches the Figma design

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-10 10:21 UTC, merged